backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Uber mich"
        name: "uber-mich"
        file: "src/_data/uber-mich.yaml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - label: "Sections"
    name: "sections"
    editor:
      preview: false
    files:
      - label: "Kurse"
        name: "kurses"
        file: "src/_data/kurses.yaml"
        fields:
          - label: Kurse
            name: kurses
            widget: list
            collapsed: false
            fields:
              - { label: Icon, name: icon, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: string }
              - { label: Price, name: price, widget: string }
              - { label: Time, name: time, widget: string } 
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Kontakts"
        name: "links"
        file: "src/_data/kontakts.yaml"
        fields:
          - label: Kontakt
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Icon, name: icon, widget: image }
              - { label: Kontakt, name: kontakt, widget: string }
      - label: "Socials"
        name: "links"
        file: "src/_data/socials.yaml"
        fields:
          - label: Socials
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Icon, name: icon, widget: image }
              - { label: URL, name: url, widget: string }        
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
